languageCode = "en"
languageName = "English"
weight = 1
title = "Ignorance is bliss..."

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "images/christoph_small.webp"
  description = "Ignorance is bliss..."

[params.author]
  name = "Christoph Cullmann"
  email = "christoph@cullmann.dev"
  image = "images/christoph_avatar.webp"
  headline = "Welcome to Christoph Cullmann's web site"
  bio = "Software Engineer at AbsInt and KDE contributor"
  links = [
    { codeberg = "https://codeberg.org/cullmann" },
    { github = "https://github.com/christoph-cullmann" },
    { gitlab = "https://gitlab.com/cullmann" },
    { reddit = "https://www.reddit.com/user/ChristophCullmann" },
    { mastodon = "https://mastodon.social/@cullmann" },
  #  { ycombinator = "https://news.ycombinator.com/user?id=cullmann" },
    { youtube = "https://youtube.com/ChristophCullmann" },
    { email = "mailto:christoph@cullmann.dev" }
  ]
