# base URL used when generating links
baseURL = "https://cullmann.dev"

# the name of the theme to use
theme = 'archie'

# basic metadata
title = "Ignorance is bliss..."
author = "Christoph Cullmann"
copyright = "Copyright © Christoph Cullmann"
languageCode = "en-US"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

[params]
  # dark theme only
  mode = "dark"

  # all stuff on my server
  useCDN = false

  # The "description" of your website. This is used in the meta data of your generated html.
  description = "Christoph Cullmann's web site"

  # Another "title" :-). This one is used as the site_name on the Hugo's internal
  # opengraph structured data template.
  # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
  title = "Ignorance is bliss..."
